apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: exhort
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: exhort
    app.kubernetes.io/part-of: exhort-alpha
  name: exhort
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: exhort
status:
  loadBalancer: {}
